services:
    #Forms
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: user_registration }
    
    #Services
    email.grabbed.handler:
        class: UserBundle\Services\EmailGrabbedHandler
        arguments: 
            - @doctrine.orm.entity_manager
            